#!/usr/bin/env python3
import sys
import os
import argparse

CLIPBOARD = os.path.expanduser("~/.copypasta")

def create_clipboard(clipboard):
    if not os.path.exists(clipboard):
        with open(clipboard, 'x') as f:
            pass

    if not os.path.isfile(clipboard):
            return 1

    return 0




if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=" Copy files in the terminal.\n\tThe clipboard is user-specific.\n\tEach copy stays in clipboard until cleared or overwritten.\n")
    parser.add_argument('file', nargs="+", metavar='FILE', help="file(s) to copy", type=str)
    files = parser.parse_args().file
    
    if create_clipboard(CLIPBOARD) != 0:
        print("ERROR: An error occured while trying to create clipboard. Please ensure that no file/folder is present previously with path '~/.copypasta'.")
        sys.exit(1)

    paths = list(map(os.path.abspath, files))
    

    exists = list(map(os.path.exists, paths))
    not_exists = []

    for i,v in enumerate(exists): 
        if not v: not_exists.append(i)

    if len(not_exists) != 0:
        print("ERROR: An error occured while trying to copy files/folders. The following files/folders do not exists:")
        for i, v in enumerate(not_exists):
            print(f"\t{i+1}. {paths[v]}")
        sys.exit(1)
        
    with open(CLIPBOARD, "w+") as f:
        f.write('\n'.join(paths))

